version: '3.9'

volumes:
  hasura-db-data: {}

services:
  hasura-db:
    container_name: sbo-hasura-db
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_DB: hasura
      POSTGRES_USER: hasura
      POSTGRES_PASSWORD: hasura
    volumes:
      - hasura-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=hasura pg_isready -U hasura -h hasura-db" ]
      interval: 10s
      timeout: 5s
      retries: 15

  hasura:
    container_name: sbo-hasura
    image: fedormelexin/graphql-engine-arm64:v2.0.8.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - hasura-db
    restart: on-failure
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura@hasura-db:5432/hasura
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_LOG_LEVEL: info
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
